name: sound_classification
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - jupyter
  - matplotlib>=3.5.0
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0
  - seaborn>=0.11.0
  - tqdm>=4.60.0
  - pip:
    - torch>=1.11.0
    - torchaudio>=0.11.0
    - transformers>=4.20.0
    - librosa>=0.9.0
    - soundfile>=0.10.0
    - tensorboard>=2.8.0
    - wandb>=0.13.0
    - audiomentations>=0.30.0 